/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank.h"

bool_t
xdr_account(xdrs, objp)
	XDR *xdrs;
	account *objp;
{

	if (!xdr_int(xdrs, &objp->id))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->sum))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_aux_struct(xdrs, objp)
	XDR *xdrs;
	aux_struct *objp;
{

	if (!xdr_int(xdrs, &objp->id))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->sum))
		return (FALSE);
	return (TRUE);
}
