/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#define MAX_ACCOUNTS 10

#include "bank.h"
#include <stdio.h>

account accountList[MAX_ACCOUNTS] ;

int checkIfAccountAlreadyExists(int _accountID)
{
    printf("LOG: checking if %d already exists...\n", _accountID);
    for (int i = 0; i < MAX_ACCOUNTS; i++)
    {
        if (accountList[i].id == _accountID)
        {
            printf("LOG: %d already exists!\n", _accountID);
            return -1;
        }
    }

    printf("LOG: %d does not exist...\n", _accountID);
    return _accountID;
}

int *
openaccount_1_svc(int *argp, struct svc_req *rqstp)
{
    static int  result;
    int accountID = *argp;

    printf("LOG: openAccount(%d) service called...\n", accountID);

    if (checkIfAccountAlreadyExists(accountID) != -1)
    {
      accountList[accountID].id = accountID;
      accountList[accountID].sum = 0;
      result = accountID;

      printf("LOG: account %d successfully created.\n\n", accountID);
    }
    else
    {
      printf("LOG: account %d was not created.\n\n", accountID);
      result = -1;
    }

    return &result;
}

int *
closeaccount_1_svc(int *argp, struct svc_req *rqstp)
{
    static int  result;
    int accountID = *argp;

    printf("LOG: closeAccount(%d) service called...\n", accountID);

    if (checkIfAccountAlreadyExists(accountID) == -1)
    {
        accountList[accountID].id = 0;
        accountList[accountID].sum = 0;
        result = 0;

        printf("LOG: account %d successfully closed.\n\n", accountID);
    }
    else
    {
      printf("LOG: account %d was not closed.\n\n", accountID);
      result = -1;
    }

    return &result;
}

int *
authaccount_1_svc(int *argp, struct svc_req *rqstp)
{
    static int  result;
    int accountID = *argp;

    result = checkIfAccountAlreadyExists(accountID);

    return &result;
}

int *
deposit_1_svc(aux_struct *argp, struct svc_req *rqstp)
{
    static int  result;

    int accountID = (*argp).id;
    float accountSum = (*argp).sum;

    printf("LOG: depositAccount(%d, %f) service called...\n", accountID, accountSum);

    if (checkIfAccountAlreadyExists(accountID) == -1)
    {
        accountList[accountID].sum = accountList[accountID].sum + accountSum;
        result = 0;

        printf("LOG: account %d successfully deposited %f.\n\n", accountID, accountSum);
    }
    else
    {
        printf("LOG: %f was not deposited in account %d.\n\n", accountSum, accountID);
        result = accountID;
    }

    return &result;
}

int *
withdraw_1_svc(aux_struct *argp, struct svc_req *rqstp)
{
  static int result;

  int accountID = (*argp).id;
  float accountSum = (*argp).sum;

  printf("LOG: withdrawAccount(%d, %f) service called...\n", accountID, accountSum);

  if (checkIfAccountAlreadyExists(accountID) == -1)
  {
      accountList[accountID].sum = accountList[accountID].sum - accountSum;
      result = 0;

      printf("LOG: account %d successfully withdrew %f.\n\n", accountID, accountSum);
  }
  else
  {
      printf("LOG: %f was not withdrawn from the account %d.\n", accountSum, accountID);
      result = accountID;
  }

  return &result;
}

float *
checkbalance_1_svc(int *argp, struct svc_req *rqstp)
{
    static float  result;

    int accountID = *argp;

    printf("LOG: checkBalance(%d) service called...\n", accountID);

    if (checkIfAccountAlreadyExists(accountID) == -1)
    {
        result = accountList[accountID].sum;

        printf("LOG: account %d just checked its balance %f.\n\n", accountID, result);
    }
    else result = -9999;

    return &result;
}
