/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <stdio.h>


struct account {
	int id;
	int balance;
};
typedef struct account account;
#ifdef __cplusplus
extern "C" bool_t xdr_account(XDR *, account*);
#elif __STDC__
extern  bool_t xdr_account(XDR *, account*);
#else /* Old Style C */
bool_t xdr_account();
#endif /* Old Style C */


struct aux_struct {
	int id;
	float sum;
};
typedef struct aux_struct aux_struct;
#ifdef __cplusplus
extern "C" bool_t xdr_aux_struct(XDR *, aux_struct*);
#elif __STDC__
extern  bool_t xdr_aux_struct(XDR *, aux_struct*);
#else /* Old Style C */
bool_t xdr_aux_struct();
#endif /* Old Style C */


#define BANK_PROG ((rpc_uint)0x12345000)
#define BANK_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define openAccount ((rpc_uint)1)
extern "C" int * openaccount_1(int *, CLIENT *);
extern "C" int * openaccount_1_svc(int *, struct svc_req *);
#define closeAccount ((rpc_uint)2)
extern "C" int * closeaccount_1(int *, CLIENT *);
extern "C" int * closeaccount_1_svc(int *, struct svc_req *);
#define authAccount ((rpc_uint)3)
extern "C" int * authaccount_1(int *, CLIENT *);
extern "C" int * authaccount_1_svc(int *, struct svc_req *);
#define deposit ((rpc_uint)4)
extern "C" int * deposit_1(aux_struct *, CLIENT *);
extern "C" int * deposit_1_svc(aux_struct *, struct svc_req *);
#define withdraw ((rpc_uint)5)
extern "C" int * withdraw_1(aux_struct *, CLIENT *);
extern "C" int * withdraw_1_svc(aux_struct *, struct svc_req *);
#define checkBalance ((rpc_uint)6)
extern "C" int * checkbalance_1(int *, CLIENT *);
extern "C" int * checkbalance_1_svc(int *, struct svc_req *);

#elif __STDC__
#define openAccount ((rpc_uint)1)
extern  int * openaccount_1(int *, CLIENT *);
extern  int * openaccount_1_svc(int *, struct svc_req *);
#define closeAccount ((rpc_uint)2)
extern  int * closeaccount_1(int *, CLIENT *);
extern  int * closeaccount_1_svc(int *, struct svc_req *);
#define authAccount ((rpc_uint)3)
extern  int * authaccount_1(int *, CLIENT *);
extern  int * authaccount_1_svc(int *, struct svc_req *);
#define deposit ((rpc_uint)4)
extern  int * deposit_1(aux_struct *, CLIENT *);
extern  int * deposit_1_svc(aux_struct *, struct svc_req *);
#define withdraw ((rpc_uint)5)
extern  int * withdraw_1(aux_struct *, CLIENT *);
extern  int * withdraw_1_svc(aux_struct *, struct svc_req *);
#define checkBalance ((rpc_uint)6)
extern  int * checkbalance_1(int *, CLIENT *);
extern  int * checkbalance_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define openAccount ((rpc_uint)1)
extern  int * openaccount_1();
extern  int * openaccount_1_svc();
#define closeAccount ((rpc_uint)2)
extern  int * closeaccount_1();
extern  int * closeaccount_1_svc();
#define authAccount ((rpc_uint)3)
extern  int * authaccount_1();
extern  int * authaccount_1_svc();
#define deposit ((rpc_uint)4)
extern  int * deposit_1();
extern  int * deposit_1_svc();
#define withdraw ((rpc_uint)5)
extern  int * withdraw_1();
extern  int * withdraw_1_svc();
#define checkBalance ((rpc_uint)6)
extern  int * checkbalance_1();
extern  int * checkbalance_1_svc();
#endif /* Old Style C */

#endif /* !_BANK_H_RPCGEN */
